name: ESLint Workflow

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: yarn add eslint eslint-plugin-jest
      - name: lint
        run: find . -name "*.js" -not -path "./node_modules/*" -not -path "./.eslintrc.js" -not -path "./.stylelintrc.js" -exec yarn eslint {} +
